apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: players.dominion.org
spec:
  scope: Namespaced
  group: dominion.org
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Player
    plural: players
    singular: player