[tool.poetry]
name = "dominion"
version = "0.9.0"
description = ""
authors = ["Gigi <the.gigi@gmail.com"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8.2"
grpcio = "^1.29.0"
grpcio-tools = "^1.29.0"
PodSixNet = "^0.11.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
