---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dominion
  labels:
    app: dominion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dominion
  template:
    metadata:
      labels:
        app: dominion
    spec:
      containers:
        - name: news-manager
          image: g1g1/dominion:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: dominion
spec:
  ports:
    - port:  50051
      targetPort: 50051
      name: grpc
  selector:
    app: dominion

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
  name: ingress-grpcs
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: dominion
          servicePort: grpc
